# Generated by Django 2.1.1 on 2018-09-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainput',
            name='number',
            field=models.CharField(max_length=5),
        ),
    ]
